[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]

[workspace.dependencies]
hdi = "=0.2.3"
hdk = "=0.1.3"
serde = "1"

[workspace.dependencies.descriptors]
path = "dnas/map_descriptors/zomes/coordinator/descriptors"

[workspace.dependencies.descriptors_integrity]
path = "dnas/map_descriptors/zomes/integrity/descriptors"
